apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
  labels:
    app: clients
spec:
  selector:
    matchLabels:
      app: clients
  template:
    metadata:
      labels:
        app: clients
    spec:
      containers:
        - name: clients
          image: nttdatabootcampacr.azurecr.io/clients:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8095
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: SPRING_CLOUD_CONFIG_PROFILE
              value: prod
      imagePullSecrets:
        - name: bootcampsecret