server:
  port: '8095'

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: clients

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'