server:
  port: '8099'

spring:
  application:
    name: clients
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'